//
// Created by diego on 10.07.22.
//

#ifndef MQTT_BROKER_CLIENT_EXAMPLE_LOCATION_DATA_GENERATOR_H
#define MQTT_BROKER_CLIENT_EXAMPLE_LOCATION_DATA_GENERATOR_H



#endif //MQTT_BROKER_CLIENT_EXAMPLE_LOCATION_DATA_GENERATOR_H
